name: Publish
on:
  workflow_dispatch:
  push:
jobs:
  pytest-coverage:
    runs-on: ubuntu-latest
    steps:
      #- name: Checkout Repository
      #  uses: actions/checkout@v2
      #- name: Install TeXLive
      #  run: "sudo apt install texlive-base texlive-lang-english texlive-lang-german texlive-latex-recommended texlive-publishers texlive-luatex"
      #- name: Setup Python
      #  uses: actions/setup-python@v2
      #  with:
      #    python-version: 3.8
      #- name: Install Dependencies
      #  run: "pip install -f https://download.pytorch.org/whl/torch_stable.html -r sys/requirements.txt"
      - name: Build Documents
        run: |
          chmod +x ./bin/build-documents.sh
          ./bin/build-documents.sh
