name: Publish
on:
  workflow_dispatch:
  #push:
jobs:
  scope:
    name: Define Scope
    runs-on: ubuntu-latest
    permissions: { }
    steps:
      - uses: haya14busa/action-cond@v1
        id: scope
        with:
          cond: ${{ github.event_name == 'workflow_dispatch' }}
          if_true: all
          if_false: changed
    outputs:
      scope: ${{ steps.scope.outputs.value }}
  documents:
    name: Collect Documents
    runs-on: ubuntu-latest
    needs: scope
    defaults:
      run:
        working-directory: .
    steps:
      - name: Collect Documents
        id: documents
        run: .github/collect-documents.sh ${{ needs.scope.outputs.scope }}
    outputs:
      documents: ${{ steps.documents.outputs.value }}
  build:
    name: Build Document
    runs-on: ubuntu-latest
    needs: documents
    defaults:
      run:
        working-directory: .
    strategy:
      matrix: ${{ fromJSON(needs.documents.outputs.documents) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Graphviz and Spin
        run: sudo apt install graphviz spin
      - name: Install TeXLive
        run: sudo apt install texlive-base texlive-fonts-extra texlive-humanities texlive-lang-cyrillic texlive-lang-english texlive-lang-german texlive-latex-extra texlive-latex-recommended texlive-latex-recommended texlive-luatex texlive-pictures texlive-plain-generic texlive-publishers texlive-science
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Python Dependencies
        run: "pip install -f https://download.pytorch.org/whl/torch_stable.html -r sys/requirements.txt"
      - name: Build Document
        run: .github/build-document.sh ${{ matrix.document }}
#  publish:
#    name: Publish Documents
#    runs-on: ubuntu-latest
#    steps:
#      - name: Publish Documents
#        run: ".github/publish-documents.sh"
#        env:
#          gh_user: ${{ secrets.PUBLISH_GH_USER }}
#          gh_token: ${{ secrets.PUBLISH_GH_TOKEN }}
